### ISSUE TITLE
VSCode `launch.json` does not work on windows

### ISSUE THREAD

**Issue by Sammy99jsp** [ESP-Number-One/MatchyoSports#25]
I thought VSCode would use powershell as a shell, which supports `program1 && program2`, but it uses normal `cmd`, so `launch.json` breaks on Windows.

**Comment by WilfSilver** [comment]
Can we not just remove `nvm use`? That was only a you thing right?

**Comment by WilfSilver** [comment]
We have finished the core development which means no one is developing on Windows anymore so this is unnecessary
