### ISSUE TITLE
Make `disabled` optional in `<Stars {...} />`

### ISSUE THREAD

**Issue by Sammy99jsp** [ESP-Number-One/MatchyoSports#45]
Typically, in HTML, `disabled` is an optional element.

You should modify your props:
- change `disabled: boolean` to `disabled?: boolean`, and 
- `disabled={props.disabled}` to `disabled={props.disabled ?? false}`.

**Comment by WilfSilver** [comment]
Closed by https://github.com/ESP-Number-One/MatchyoSports/pull/48
